### ISSUE TITLE
Upgrade to newer Chromium version

### ISSUE THREAD

**Issue by raflow** [tejzpr/webex-teams-linux#1]
Hi,
First, thanks for your contribution, it really fills the gap for us Linux users who are forgotten by Cisco.
I would like to ask you to upgrade the embedded chromium version so we can use the videoconference feature, the error message shown is  "Your Chrome version is: 59.0 Please update Chrome to version 60 or greater."
Thanks in advance

**Comment by chris-gibbs** [comment]
Hey,

I was able to wrap the webex teams app using Nativefier.

https://github.com/jiahaog/nativefier

then used:
nativefier -n "Webex Teams" -p linux -a x64 -e 4.2.3 -i icon.png --tray https://teams.webex.com

to generate the wrapped package. That is for the latest version of Eletron as of today. Check 
https://github.com/electron/electron/releases for the version that you need.

I haven't tested all the functionality but i know it has stopped complaining regarding the version of Chrome :) 

Cheers,

Chris

**Comment by jonhowe** [comment]
Thanks for this @chris-gibbs ! I admittedly don't know much about electron, but nativefier made this super easy.
Cheers!

**Comment by mdunc** [comment]
That's an awesome suggestion @chris-gibbs!  The only thing I would suggest is to use the --single-instance flag.  That way, if you have it pinned to the docker and minimized to the system tray, clicking the dock icon to go back to it won't open a whole new instance of it.

**Comment by raflow** [comment]
I also used nativefier and it worked like a charm. The only flaw is the Share Screen feature is disabled, but A/V conference and chat work really well
Thanks @chris-gibbs !

**Comment by leinardi** [comment]
@chris-gibbs thanks for the suggestion! It works really well! I used also the suggestion from @mdunc regarding the single instance and changed the Electron version to the current latest stable (5.0.4):
```
nativefier --name "Webex-Teams" --platform linux --arch x64 --electron-version 5.0.4 --icon /path/to/cisco-webex-teams.png --tray --single-instance --counter --bounce --honest https://teams.webex.com
```
([icon](https://user-images.githubusercontent.com/273338/59764741-aefed300-929c-11e9-8766-4942486d9f55.png))

Issues I've found so far:

1. Desktop sharing doesn't work (like @rafaedoras already reported)
2. The tray icon doesn't show the unread messages count (like Telegram does, for example)
3. No option to store credentials (I have to relogin every time I re-open the app)
4. Unread messages counter on the App title reset to the default title as soon as the mouse get closer to the Electron window

**Comment by leinardi** [comment]
Almost 1 year later there is still no native client, and the current web version of WebEx Teams does not provide the same features as the Mac and Windows native clients. You cannot edit your messages, you cannot add or even view reactions and most of the time the chat history goes crazy and you don't see new messages anymore.

And yes, I know that there is a long running beta version that fixes some of these issues, but the beta version doesn't allow to make or join audio/video calls! And, in these quarantine days, being able to join call conferences is a must.

Please consider voting on the official Cisco User Community Feedback the entry for a native Linux client:
https://ciscocollabcustomer.ideas.aha.io/ideas/WXCUST-I-61

**Comment by mdunc** [comment]
I am aware that Cisco does indeed have a Linux Webex Teams client available internally to Cisco employees.  It would very useful if that was released to the public.

**Comment by leinardi** [comment]
> I am aware that Cisco does indeed have a Linux Webex Teams client available internally to Cisco employees.

Really? I don't know if I should be happy or even more pissed than I already am. It's so frustrating to have to continuously switch between being able to make calls and being able to see reactions and edit messages due to their awful web version.

**Comment by mdunc** [comment]
[removed just to be on the safe side.  that may have been something confidential that was shared with me and I'd rather him not be cross with me in case this got out and became a big deal]

**Comment by tejzpr** [comment]
I apologize in the delay in responding to this issue. I have released a new version based on the latest Electron, therefore closing this issue.
