### ISSUE TITLE
Error message when attempting to sign-in

### ISSUE THREAD

**Issue by jgmitchell257** [tejzpr/webex-teams-linux#3]
I receive a "Not a valid SAML 2.0 Request Message!" error message from my SSO provider when attempting to sign-in through the application. Not sure if it comes from the app itself or WebEx, but I am able to sign-in through the web with no issue.

**Comment by tejzpr** [comment]
Cisco has released Webex for Linux. That would be the recommended way to access Webex (Webex Teams) on linux from now on. This repository will not be maintained anymore. 
https://help.webex.com/en-us/9vstcdb/Webex-for-Linux
https://www.webex.com/downloads.html

**Comment by jgmitchell257** [comment]
Awesome, thank you very much. I hadn't seen an announcement for it.
